### ISSUE TITLE
Support for setting frame rate? (FPS)

### ISSUE THREAD

**Issue by mrwm** [peterbay/camera-control#3]
From what I've found searching around, setting frame rate can be done with `v4l2-ctl --set-parm=8` to set 8.0 FPS, as seen [in this stackexchange post](https://raspberrypi.stackexchange.com/questions/46571/how-to-specify-fps-frame-rate-when-streaming-video-with-uv4l#). Is there support for changing the FPS here?

**Comment by peterbay** [comment]
Hi, FPS control added.
The maximum value is limited by -f parameter in the range between 1 and 120 and the default value 30.

**Comment by mrwm** [comment]
Thanks for the update!
