### ISSUE TITLE
settings are cleared when rebooted

### ISSUE THREAD

**Issue by seanreynoldscs** [peterbay/camera-control#6]
I'm not sure how to get the settings to persist after reboot.

**Comment by peterbay** [comment]
You can create a small shell script for applying your selected controls.
And run it after boot - [How to Run Linux Commands and Scripts Automatically on a System Reboot](https://linuxhint.com/run_linux_command_script_sys_reboot/)

It's based on [start-webcam.sh from showmewebcam](https://github.com/showmewebcam/showmewebcam/blob/master/package/piwebcam/start-webcam.sh)

```
#!/bin/sh

# for device /dev/video0 use value 0
DEVICE="0"
# path to config file created by camera-ctl
CONFIG_FILE="/boot/camera.txt"

if [ -f "${CONFIG_FILE}" ] ; then
  cat "${CONFIG_FILE}" | sed "s/ //g" | grep "\S" | grep -vE "^\#" | while read -r line
  do
    KEY=$(echo "$line" | cut -d= -f1)
    VAL=$(echo "$line" | cut -d= -f2)
    echo "Setting $KEY -> $VAL"
    /usr/bin/v4l2-ctl -d "${DEVICE}" -c "${KEY}"="${VAL}"
  done
else
  echo "File ${CONFIG_FILE} not found"
fi
```
